name: Azure Static Web Apps CI/CD

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          cache: "npm"

      - name: Install & Build (Vite)
        run: |
          npm ci || npm install
          npm run build

      # Sanity check the token is present (optional but helpful)
      - name: Preflight token length
        env:
          SWA_TOKEN: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_AGREEABLE_STONE_05CA5041E }}
        run: |
          if [ -z "${SWA_TOKEN}" ]; then echo "Missing SWA token secret"; exit 1; fi
          echo "SWA token looks present."

      - name: Upload to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          action: upload
          app_location: "/"              # repo root (just for logs)
          app_artifact_location: "dist"  # upload the build output
          skip_app_build: true
          production_branch: "main"
          deployment_environment: "Production"
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_AGREEABLE_STONE_05CA5041E }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    steps:
      - name: Close PR Environment
        uses: Azure/static-web-apps-deploy@v1
        with:
          action: close
          app_location: "/"
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_AGREEABLE_STONE_05CA5041E }}
