name: Azure Static Web Apps CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches: [ main ]

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          cache: "npm"

      - name: Install & Build (Vite)
        run: |
          npm ci || npm install
          npm run build

      # Sanity check the secret (doesn't print it)
      - name: Validate SWA token
        shell: bash
        env:
          SWA_TOKEN: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_AGREEABLE_STONE_05CA5041E }}
        run: |
          if [ -z "${SWA_TOKEN}" ]; then echo "Missing SWA token secret"; exit 1; fi
          LEN=${#SWA_TOKEN}
          if [ "$LEN" -lt 100 ]; then echo "Token too short ($LEN)"; exit 1; fi
          if printf '%s' "$SWA_TOKEN" | grep -qE '[[:space:]]'; then echo "Token contains whitespace"; exit 1; fi
          echo "SWA token length OK: $LEN"

      - name: Build And Deploy (SWA)
        uses: Azure/static-web-apps-deploy@v1
        with:
          action: upload
          app_location: "/"           # repo root
          output_location: "dist"     # Vite output
          skip_app_build: true        # we already built
          config_file_location: "public"  # where staticwebapp.config.json lives
          production_branch: "main"
          deployment_environment: "Production"
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_AGREEABLE_STONE_05CA5041E }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    steps:
      - name: Close PR Environment
        uses: Azure/static-web-apps-deploy@v1
        with:
          action: close
          app_location: "/"
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_AGREEABLE_STONE_05CA5041E }}
