name: SWA Deploy (OIDC)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          cache: "npm"

      - name: Install & Build (Vite)
        run: |
          npm ci || npm i
          npm run build

      - name: Azure login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      # (Optional) sanity print
      - name: Whoami
        run: az account show --query "{tenantId:tenantId, subscription:id, user:user.name}"

      - name: Get SWA deployment token (via OIDC)
        run: echo "SWA_TOKEN=$(az staticwebapp secrets list -g tabarnam-mvp-rg -n tabarnam-frontend --query properties.apiKey -o tsv)" >> $GITHUB_ENV

      # Use the official SWA deploy action, but feed it the token we just fetched
      - name: Upload to Static Web Apps (app + api)
        uses: Azure/static-web-apps-deploy@v1
        with:
          action: upload
          app_location: "/"
          app_artifact_location: "dist"
          skip_app_build: true
          api_location: "api"
          azure_static_web_apps_api_token: ${{ env.SWA_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
