name: SWA Deploy (OIDC)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      RG_NAME: tabarnam-mvp-rg
      SWA_NAME: tabarnam-frontend
      SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          cache: "npm"

      - name: Install & Build (Vite)
        run: |
          npm ci || npm i
          npm run build
          test -d dist || (echo "dist/ missing" && exit 1)

      - name: Azure login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Who am I (debug)
        run: az account show --query "{tenantId:tenantId, subscription:id, user:user.name}"

      - name: "Debug: SWA identity"
        run: |
          az staticwebapp show -g "$RG_NAME" -n "$SWA_NAME" \
            --query "{name:name, id:id, host:defaultHostname, location:location}" -o tsv

      # Rotate the deployment token (ensures it’s valid)
      - name: Rotate SWA deployment token
        id: token
        run: |
          NEW=$(az staticwebapp secrets reset-api-key -g "$RG_NAME" -n "$SWA_NAME" --query properties.apiKey -o tsv)
          if [ -z "$NEW" ]; then
            echo "Failed to obtain deployment token"; exit 1
          fi
          echo "::add-mask::$NEW"
          echo "value=$NEW" >> "$GITHUB_OUTPUT"

      # Official deploy action with the fresh token
      - name: Deploy to Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          action: upload
          azure_static_web_apps_api_token: ${{ steps.token.outputs.value }}
          app_location: /
          output_location: dist
          api_location: api
          skip_app_build: true
          production_branch: main

      - name: Post-deploy health check (non-fatal)
        run: |
          HOST=$(az staticwebapp show -g "$RG_NAME" -n "$SWA_NAME" --query defaultHostname -o tsv)
          echo "Host: https://$HOST"
          echo "Home page ping:"
          curl -sS --retry 5 --retry-delay 5 "https://$HOST" | head -c 200 || true
          echo
          echo "Proxy smoke test (GET /api/proxy-xai):"
          curl -sS "https://$HOST/api/proxy-xai" || true
