name: SWA Deploy (upload dist + api)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          cache: "npm"

      - name: Install & Build (Vite)
        run: |
          npm ci || npm install
          npm run build

      - name: Preflight token
        env:
          SWA_TOKEN: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
        run: |
          if [ -z "$SWA_TOKEN" ]; then
            echo "Missing AZURE_STATIC_WEB_APPS_API_TOKEN secret"; exit 1;
          fi
          echo "SWA token present (length: ${#SWA_TOKEN})"
          # Fail fast if the token has any whitespace/newlines
          if echo "$SWA_TOKEN" | tr -d '[:print:]' | grep -q .; then
            echo "Token contains non-printable characters (likely newline). Re-save the secret as a single line."; exit 1;
          fi
          if echo "$SWA_TOKEN" | grep -q '[[:space:]]'; then
            echo "Token contains whitespace. Re-save the secret as a single line."; exit 1;
          fi
          echo "Token format looks good."

      - name: Upload to Azure Static Web Apps (app + api)
        uses: Azure/static-web-apps-deploy@v1
        with:
          action: upload
          app_location: "/"
          app_artifact_location: "dist"
          skip_app_build: true
          api_location: "api"
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
