# .github/workflows/swa-deploy.yml
name: SWA Deploy (OIDC)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      RG_NAME: tabarnam-mvp-rg
      SWA_NAME: tabarnam-frontend
      SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          cache: "npm"

      - name: Install & Build (Vite)
        run: |
          npm ci || npm i
          npm run build
          test -d dist || (echo "dist/ missing" && exit 1)

      - name: Azure login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Who am I (debug)
        run: az account show --query "{tenantId:tenantId, subscription:id, user:user.name}"

      - name: "Debug: SWA identity"
        run: |
          az staticwebapp show -g "$RG_NAME" -n "$SWA_NAME" \
            --query "{name:name, id:id, host:defaultHostname, location:location}" -o tsv

      - name: Ensure SWA az extension (latest)
        run: az extension add --name staticwebapp -y || az extension update --name staticwebapp

      # --- NEW: get a fresh deployment token reliably via ARM REST ---
      - name: Get SWA deployment token (ARM regenerate or list)
        id: token
        shell: bash
        run: |
          set -euo pipefail
          SITE_ID="$(az staticwebapp show -g "$RG_NAME" -n "$SWA_NAME" --query id -o tsv)"
          API="https://management.azure.com${SITE_ID}/regenerateApiKey?api-version=2022-03-01"
          echo "Regenerating token via ARM: $API"
          NEW="$(az rest --method post --uri "$API" --query properties.apiKey -o tsv || true)"
          if [ -z "${NEW:-}" ]; then
            echo "Regenerate returned empty; falling back to list..."
            NEW="$(az staticwebapp secrets list -g "$RG_NAME" -n "$SWA_NAME" --query properties.apiKey -o tsv || true)"
          fi
          if [ -z "${NEW:-}" ]; then
            echo "Failed to obtain deployment token"; exit 1
          fi
          echo "::add-mask::$NEW"
          echo "value=$NEW" >> "$GITHUB_OUTPUT"
          echo "Token length: ${#NEW}"
          printf "%s" "$NEW" | sha256sum | cut -c1-12 | xargs echo "sha256 prefix:"

      - name: Deploy to Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          action: upload
          azure_static_web_apps_api_token: ${{ steps.token.outputs.value }}
          app_location: /
          output_location: dist
          api_location: api
          skip_app_build: true
          production_branch: main
          deployment_environment: production

      - name: Post-deploy health check (non-fatal)
        run: |
          SwaHost=$(az staticwebapp show -g "$RG_NAME" -n "$SWA_NAME" --query defaultHostname -o tsv)
          echo "Host: https://$SwaHost"
          echo "Home page ping:"
          curl -sS --retry 5 --retry-delay 5 "https://$SwaHost" | head -c 200 || true
          echo
          echo "Proxy smoke test (GET /api/proxy-xai):"
          curl -sS "https://$SwaHost/api/proxy-xai" || true
