name: SWA Deploy (OIDC)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      RG_NAME: tabarnam-mvp-rg
      SWA_NAME: tabarnam-frontend

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          cache: "npm"

      - name: Install & Build (Vite)
        run: |
          npm ci || npm i
          npm run build

      - name: Azure login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Who am I (debug)
        run: az account show --query "{tenantId:tenantId, subscription:id, user:user.name}"

      - name: Fetch SWA deployment token and export for action
        run: |
          TOKEN=$(az staticwebapp secrets list -g "$RG_NAME" -n "$SWA_NAME" --query properties.apiKey -o tsv)
          echo "AZURE_STATIC_WEB_APPS_API_TOKEN=$TOKEN" >> "$GITHUB_ENV"

      - name: Deploy to Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          action: "upload"
          azure_static_web_apps_api_token: ${{ env.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          app_location: /
          output_location: dist
          api_location: api
          skip_app_build: true
          production_branch: main

      - name: Post-deploy health check (non-fatal)
        run: |
          HOST=$(az staticwebapp show -g "$RG_NAME" -n "$SWA_NAME" --query defaultHostname -o tsv)
          echo "Host: https://$HOST"
          echo "Home page ping:"
          curl -sS --retry 5 --retry-delay 5 "https://$HOST" | head -c 200 || true
          echo
          echo "Proxy smoke test:"
          curl -sS -X POST "https://$HOST/api/proxy-xai" \
               -H "Content-Type: application/json" \
               -d '{"queryType":"product_keyword","query":"gelato machine","limit":1}' || true
