name: SWA Deploy (OIDC)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      RG_NAME: tabarnam-mvp-rg
      SWA_NAME: tabarnam-frontend

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          cache: "npm"

      - name: Install & Build (Vite)
        run: |
          npm ci || npm i
          npm run build

      - name: Azure login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Who am I (debug)
        run: az account show --query "{tenantId:tenantId, subscription:id, user:user.name}"

      - name: Ensure az staticwebapp extension
        run: az extension add --name staticwebapp -y || az extension update --name staticwebapp

      - name: Dump SWA identity & host (triple-check targeting)
        run: |
          az staticwebapp show -g "$RG_NAME" -n "$SWA_NAME" \
            --query "{name:name, id:id, region:location, host:defaultHostname}" -o tsv

      - name: Deploy via Azure CLI (no token)
        run: |
          set -euxo pipefail
          # Push built site + API to the SWA resource you logged into via OIDC
          az staticwebapp upload \
            -g "$RG_NAME" \
            -n "$SWA_NAME" \
            --app-artifact-location "dist" \
            --api-location "api" \
            --verbose

      - name: Post-deploy health check (non-fatal)
        run: |
          HOST=$(az staticwebapp show -g "$RG_NAME" -n "$SWA_NAME" --query defaultHostname -o tsv)
          echo "Host: https://$HOST"
          echo "GET / ->"
          curl -sS --retry 5 --retry-delay 3 "https://$HOST" | head -c 200 || true
          echo
          echo "GET /api/proxy-xai ->"
          curl -sS --retry 3 --retry-delay 2 "https://$HOST/api/proxy-xai" | head -c 300 || true
          echo
          echo "POST /api/proxy-xai (stub body) ->"
          curl -sS -X POST "https://$HOST/api/proxy-xai" \
               -H "Content-Type: application/json" \
               -d '{"queryType":"product_keyword","query":"gelato machine","limit":1}' \
               | head -c 400 || true
