# .github/workflows/swa-deploy.yml
name: SWA Deploy (OIDC)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

concurrency:
  group: swa-deploy-prod
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      RG_NAME: tabarnam-mvp-rg
      SWA_NAME: tabarnam-frontend

    steps:
      - uses: actions/checkout@v4

      # Build the Vite app up-front to keep the SWA action simple
      - uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          cache: "npm"

      - name: Install & Build (Vite)
        run: |
          npm ci || npm i
          npm run build

      # Quick sanity: show the hash prefix of the repo secret
      - name: Show token SHA256 prefix (repo secret)
        shell: bash
        run: |
          printf "repo secret sha256: "
          echo -n '${{ secrets.SWA_DEPLOYMENT_TOKEN }}' | sha256sum | cut -c1-12

      # Login just to compare Azure's token vs your repo secret (hashes only)
      - name: Azure login (OIDC) for token compare + health checks
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id:  ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Compare token with Azure listSecrets (hash only)
        shell: bash
        run: |
          AZ_TOKEN=$(az rest --method post \
            --url "https://management.azure.com/subscriptions/${{ secrets.AZURE_SUBSCRIPTION_ID }}/resourceGroups/${RG_NAME}/providers/Microsoft.Web/staticSites/${SWA_NAME}/listSecrets?api-version=2023-12-01" \
            --query "properties.apiKey" -o tsv)
          printf "azure listSecrets sha256: "
          echo -n "$AZ_TOKEN" | sha256sum | cut -c1-12
          printf "repo secret sha256:    "
          echo -n '${{ secrets.SWA_DEPLOYMENT_TOKEN }}' | sha256sum | cut -c1-12

      # Deploy using the official SWA action with your portal token
      - name: Deploy to Static Web Apps (token)
        uses: Azure/static-web-apps-deploy@v1
        with:
          action: "upload"
          azure_static_web_apps_api_token: ${{ secrets.SWA_DEPLOYMENT_TOKEN }}
          app_location: "."               # repo root
          output_location: "dist"         # built Vite output
          api_location: "api"             # Functions folder
          skip_app_build: true            # already built
          skip_api_build: false           # package API
          production_branch: "main"

      - name: Post-deploy health checks (non-fatal)
        shell: bash
        run: |
          HOST=$(az staticwebapp show -g "$RG_NAME" -n "$SWA_NAME" --query defaultHostname -o tsv)
          echo "Host: https://$HOST"
          echo "GET / ->"
          curl -sS --retry 5 --retry-delay 3 "https://$HOST" | head -c 200 || true
          echo
          echo "GET /api/proxy-xai ->"
          curl -sS --retry 3 --retry-delay 2 "https://$HOST/api/proxy-xai" | head -c 300 || true
          echo
          echo "POST /api/proxy-xai (stub body) ->"
          curl -sS -X POST "https://$HOST/api/proxy-xai" \
               -H "Content-Type: application/json" \
               -d '{"queryType":"product_keyword","query":"gelato machine","limit":1}' \
               | head -c 400 || true
