name: SWA Deploy (upload dist + api)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          cache: "npm"

      - name: Install & Build (Vite)
        run: |
          npm ci || npm install
          npm run build

      - name: Preflight token
        env:
          SWA_TOKEN: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
        run: |
          if [ -z "$SWA_TOKEN" ]; then echo "Missing AZURE_STATIC_WEB_APPS_API_TOKEN secret"; exit 1; fi
          echo "SWA token present."

      - name: Upload to Azure Static Web Apps (app + api)
        uses: Azure/static-web-apps-deploy@v1
        with:
          action: upload
          app_location: "/"
          app_artifact_location: "dist"
          skip_app_build: true         # we already ran npm run build
          api_location: "api"          # <-- THIS makes it deploy /api
          # do NOT skip API build so the action packs the functions
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
